services:
  my-home-library:
    command: [ "./server", "-env=prod" ]
    env_file:
      - .env.prod

  redis:
    env_file:
      - .env.prod

  mysql:
    env_file:
      - .env.prod

  zookeeper:
    env_file:
      - .env.prod

  kafka:
    env_file:
      - .env.prod
